export const seedData = {
  users: [
    {
      id: 1,
      name: 'Admin User',
      email: 'admin@demo.com',
      password: 'password',
      role: 'admin',
      createdAt: new Date().toISOString(),
    },
    {
      id: 2,
      name: 'Manager User',
      email: 'manager@demo.com',
      password: 'password',
      role: 'manager',
      createdAt: new Date().toISOString(),
    },
    {
      id: 3,
      name: 'Supplier User',
      email: 'supplier@demo.com',
      password: 'password',
      role: 'supplier',
      createdAt: new Date().toISOString(),
    },
  ],
  products: [
    {
      id: 1,
      name: 'Rice 5kg',
      description: 'Premium basmati rice',
      price: 400,
      stock: 12,
      threshold: 10,
      category: 'Grocery',
      sku: 'RICE-5KG-001',
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=300&fit=crop',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 2,
      name: 'Toothpaste',
      description: 'Fluoride toothpaste 100g',
      price: 80,
      stock: 2,
      threshold: 5,
      category: 'Personal Care',
      sku: 'TP-100G-001',
      unit: 'pcs',
      image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&h=300&fit=crop',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 3,
      name: 'Cooking Oil 1L',
      description: 'Sunflower cooking oil',
      price: 150,
      stock: 0,
      threshold: 3,
      category: 'Grocery',
      sku: 'OIL-1L-001',
      unit: 'L',
      image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=300&fit=crop',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 4,
      name: 'Milk 1L',
      description: 'Fresh whole milk',
      price: 60,
      stock: 25,
      threshold: 10,
      category: 'Dairy',
      sku: 'MILK-1L-001',
      unit: 'L',
      image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=300&fit=crop',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 5,
      name: 'Bread Loaf',
      description: 'White bread loaf',
      price: 40,
      stock: 8,
      threshold: 5,
      category: 'Grocery',
      sku: 'BREAD-001',
      unit: 'pcs',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  orders: [
    {
      id: 1,
      productId: 2,
      quantity: 20,
      status: 'pending',
      requestedBy: 2,
      supplierId: 3,
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      id: 2,
      productId: 3,
      quantity: 10,
      status: 'shipped',
      requestedBy: 1,
      supplierId: 3,
      createdAt: new Date(Date.now() - 172800000).toISOString(),
      updatedAt: new Date(Date.now() - 86400000).toISOString(),
    },
  ],
  notifications: [
    {
      id: 1,
      type: 'LOW_STOCK',
      title: 'Low Stock Alert',
      message: 'Toothpaste stock is below threshold (2 units)',
      read: false,
      productId: 2,
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: 2,
      type: 'ORDER_SHIPPED',
      title: 'Order Shipped',
      message: 'Order #2 has been shipped',
      read: false,
      orderId: 2,
      createdAt: new Date(Date.now() - 7200000).toISOString(),
    },
  ],
};

